#!/usr/bin/env node
'use strict';
// make_reg_pm.js — generate the Ensembl registry (reg.pm) for this release from
// gramene-mongodb/ensembl_db_info.json, so the registry can never drift from the databases the
// build actually used.
//
//   node make_reg_pm.js > reg.pm
//
// Emits a core stanza per genome, a variation stanza per variation db, and one compara stanza.
// The species name is the core database's stem (everything before "_core_"), which is exactly
// maps.system_name — verified for all 128 cores of the v11 build.
//
// NB this writes the RELEASE's registry. The live REST server reads
// /usr/local/ensembl-87/ensembl-rest/reg.pm, which is shared by every subsite (91 species:
// vitis, oryza, sorghum, populus, …). Do not overwrite that with this file — merge the sorghum
// stanzas into it, leaving the other subsites' entries alone.

const path = require('path');
const INFO = process.env.ENSEMBL_DB_INFO ||
  path.join(__dirname, '..', 'gramene-mongodb', 'ensembl_db_info.json');
const info = require(INFO);

const host = info.compara.host;
const user = info.compara.user;
const pass = info.compara.password || '';
const port = 3306;

const stem = db => db.replace(/_core_.*$/, '').replace(/_variation_.*$/, '');

const out = [];
out.push('# Ensembl registry for the SorghumBase v11 release.');
out.push('# GENERATED by build/make_reg_pm.js from gramene-mongodb/ensembl_db_info.json —');
out.push('# regenerate rather than hand-editing, so it cannot drift from the build.');
out.push('#   compara:    ' + info.compara.database);
out.push('#   cores:      ' + info.cores.length);
out.push('#   variations: ' + info.variations.length);
out.push('');
out.push('use Bio::EnsEMBL::DBSQL::DBAdaptor;');
out.push('use Bio::EnsEMBL::Compara::DBSQL::DBAdaptor;');
out.push('use Bio::EnsEMBL::Variation::DBSQL::DBAdaptor;');
out.push('use Bio::EnsEMBL::Registry;');
out.push('');
out.push('Bio::EnsEMBL::Registry->no_version_check(1);');
out.push('Bio::EnsEMBL::Registry->no_cache_warnings(1);');
out.push('');
out.push("my $grm_user = '" + user + "';");
out.push("my $grm_pass = '" + pass + "';");
out.push("my $grm_host = '" + host + "';");
out.push('my $grm_port = ' + port + ';');
out.push('');

function stanza(adaptor, species, group, dbname) {
  return [
    adaptor + '->new(',
    "    -species => '" + species + "',",
    "    -group   => '" + group + "',",
    '    -port    => $grm_port,',
    '    -host    => $grm_host,',
    '    -user    => $grm_user,',
    '    -pass    => $grm_pass,',
    '    -dbname  => "' + dbname + '"',
    ');',
    ''
  ].join('\n');
}

out.push('# ---- core databases (' + info.cores.length + ') ----------------------------------');
out.push('');
info.cores.slice().sort((a, b) => a.database.localeCompare(b.database)).forEach(c => {
  out.push(stanza('Bio::EnsEMBL::DBSQL::DBAdaptor', stem(c.database), 'core', c.database));
});

out.push('# ---- variation databases (' + info.variations.length + ') ------------------------');
out.push('');
info.variations.forEach(v => {
  out.push(stanza('Bio::EnsEMBL::Variation::DBSQL::DBAdaptor', stem(v.database), 'variation', v.database));
});

out.push('# ---- compara ---------------------------------------------------------------');
out.push('');
out.push(stanza('Bio::EnsEMBL::Compara::DBSQL::DBAdaptor', 'sorghum', 'compara', info.compara.database));

out.push('my $REG = \'Bio::EnsEMBL::Registry\';');
out.push('');
out.push("$REG->add_alias( 'sorghum_bicolor',            'Sorghum_bicolor' );");
out.push("$REG->add_alias( 'sorghum_bicolor',            'sorghum bicolor' );");
out.push('');
out.push('1;');

process.stdout.write(out.join('\n') + '\n');
